var Reader=function(a){this.index=0;this.buffer=a};Reader.prototype.readInt8=function(){return this.buffer.readInt8(this.index++)};Reader.prototype.readUInt8=function(){return this.buffer.readUInt8(this.index++)};Reader.prototype.readInt16=function(a){this.index+=2;return a?this.buffer.readInt16LE(this.index-2):this.buffer.readInt16BE(this.index-2)};Reader.prototype.readUInt16=function(a){this.index+=2;return a?this.buffer.readUInt16LE(this.index-2):this.buffer.readUInt16BE(this.index-2)};
Reader.prototype.readInt32=function(a){this.index+=4;return a?this.buffer.readInt32LE(this.index-4):this.buffer.readInt32BE(this.index-4)};Reader.prototype.readUInt32=function(a){this.index+=4;return a?this.buffer.readUInt32LE(this.index-4):this.buffer.readUInt32BE(this.index-4)};Reader.prototype.readInt64=function(a){this.index+=8;return a?this.buffer.readBigInt64LE(this.index-8):this.buffer.readBigInt64BE(this.index-8)};
Reader.prototype.readUInt64=function(a){this.index+=8;return a?this.buffer.readBigUInt64LE(this.index-8):this.buffer.readBigUInt64BE(this.index-8)};Reader.prototype.readFloat32=function(a){this.index+=4;return a?this.buffer.readFloatLE(this.index-4):this.buffer.readFloatBE(this.index-4)};Reader.prototype.readFloat64=function(a){this.index+=8;return a?this.buffer.readFloat64LE(this.index-8):this.buffer.readFloat64BE(this.index-8)};
Reader.prototype.readString8=function(){for(var a="";;){var b=this.readUInt8();if(0==b)break;a+=String.fromCharCode(b)}return a};Reader.prototype.readString16=function(a){var b="";for(a=a||!1;;){var c=this.readUInt16(a);if(0==c)break;b+=String.fromCharCode(c)}return b};Reader.prototype.readString32=function(a){var b="";for(a=a||!1;;){var c=this.readUInt32(a);if(0==c)break;b+=String.fromCharCode(c)}return b};var Writer=function(a){this.index=0;this.buffer=Buffer.alloc(a)};
Writer.prototype.toBuffer=function(){return this.buffer};Writer.prototype.reset=function(){this.index=0;return this};Writer.prototype.writeInt8=function(a){this.buffer.writeInt8(a,this.index++);return this};Writer.prototype.writeUInt8=function(a){this.buffer.writeUInt8(a,this.index++);return this};Writer.prototype.writeInt16=function(a,b){b?this.buffer.writeInt16LE(a,this.index):this.buffer.writeInt16BE(a,this.index);this.index+=2;return this};
Writer.prototype.writeUInt16=function(a,b){b?this.buffer.writeUInt16LE(a,this.index):this.buffer.writeUInt16BE(a,this.index);this.index+=2;return this};Writer.prototype.writeInt32=function(a,b){b?this.buffer.writeInt32LE(a,this.index):this.buffer.writeInt32BE(a,this.index);this.index+=4;return this};Writer.prototype.writeUInt32=function(a,b){b?this.buffer.writeUInt32LE(a,this.index):this.buffer.writeUInt32BE(a,this.index);this.index+=4;return this};
Writer.prototype.writeInt64=function(a,b){b?this.buffer.writeBigInt64LE(a,this.index):this.buffer.writeBigInt64BE(a,this.index);this.index+=8;return this};Writer.prototype.writeUInt64=function(a,b){b?this.buffer.writeBigUInt64LE(a,this.index):this.buffer.writeBigUInt64BE(a,this.index);this.index+=8;return this};Writer.prototype.writeFloat32=function(a,b){b?this.buffer.writeFloatLE(a,this.index):this.buffer.writeFloatBE(a,this.index);this.index+=4;return this};
Writer.prototype.writeFloat64=function(a,b){b?this.buffer.writeFloat64LE(a,this.index):this.buffer.writeFloat64BE(a,this.index);this.index+=8;return this};Writer.prototype.writeString8=function(a){if("string"===typeof a){for(var b in a)this.writeUInt8(a.charCodeAt(b));return this.writeUInt8(0)}};Writer.prototype.writeString16=function(a,b){if("string"===typeof a){b=b||!1;for(var c in a)this.writeUInt16(a.charCodeAt(c),b);return this.writeUInt16(0)}};
Writer.prototype.writeString32=function(a,b){if("string"===typeof a){b=b||!1;for(var c in a)this.writeUInt32(a.charCodeAt(c),b);return this.writeUInt32(0)}};module.exports={Writer:Writer,Reader:Reader};

return {Reader: Reader, Writer: Writer}